name: Deploy

on:
  workflow_run:
    workflows:
      - Unit tests
#    branches:
#      - main
    types:
      - completed

jobs:
  deploy-packages:
    runs-on: ubuntu-latest

    # the 2nd condition
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install .
      - name: Run Sphinx
        run: |
          cd docs
          make html
